Consistently treat server port as a string
Loading the object from other sources produces a string, so we'll make the cli argument a string too.

Fixes exception:

    File "datacube-ensure-user.py", line 84, in append_credentials
    fout.write(':'.join(dbcreds) + '\n')
    TypeError: sequence item 1: expected str instance, int found